let questions = [
    'har mest milf mor',
    'har den fineste søsteren',
    'skal chugge resten av glasset', 
    'hadde du donert en nyre til',
    'kommer til å dø av koffein overdose',
    'er mest biff',
    'er den mest skittne i senga',
    'hadde sett best ut som en jente',
    'er mest keeg? s/o @groggymenn2 ',
    'hadde du ikke latt søsteren din ha med hjem',
    'drar ikke hjem med en dame idag',
    'drar til asia for å finne seg kone',
    'har hatt klamydia flest ganger',
    'tar med seg smårips hjem fra byen',
    'månedlig abonnement på tinder gold',
    "er mest skitten",
    "suger til å chugge",
    "har mest draget",
    "hadde du vært homo for",
    "hadde sett best ut som motsatt kjønn",
    "blir en sugar daddy",
    "blør neseblod imorgen",
    "finner seg en sugarmomma",
    "går på roids i skjul",
    "sender flest snaps på gymmen",
    "blir homo på fylla",
    "skal sette på neste sang",
    "slepper ikke inn på byen ikveld",
    "må drikke mer",
    "kan ikke alfabetet",
    "har værst moves",
    "har best moves",
    "tror de kan synge",
    "prøver seg mest på russ",
    "har shavet og er klar for alt",
    "bruker mest på byen",
    "har størst baller",
    "skal på hval-jakt ikveld",
    "er mest romantisk",
    "eier ikke spikeren i veggen",
    "har en indre kunstner i seg",
    "liker føtter",
    "er en milf-hunter",
    "er en midget",
    "er mest alpha",
    "er mest beta",
    "ville du vært på en øde øy med",
    "er mest selvopptatt",
    "er mest sannsynlig til å kjøre i fylla",
    "runker opp til 5 ganger om dagen",
    "er mest pliktoppfyllende",
    "bruker mest på gucci klær",
    "flekser penger",
    "lager diggest mat",
    "lager de beste drinkene",
    "ser seg mest i speilet",
    "er et englebarn",
    "er djevelen på skulderen",
    "er svigermors drøm",
    "er mest bortkjemt",
    "blir kjendis",
    "er whipped av dama",
    "har villa med basseng om 10 år",
    "sløser mest penger",
    "er mest cocky",
    "ser på hentai",
    "er størst gamer",
    "havner i fengsel",
    "rømmer til mexico",
    "er mest svett gamer",
    "får barn først",
    "bor lengst hos foreldrene sine",
    "spyr ikveld",
    "melder seg på ex on the beach",
    "er alltid med på fylla",
    "går på byen alene",
    "burde stoppe å spise på maccern",
    "er mest på mobilen",
    "er med i mile high club",
    "krangler mest med vektere",
    "hat tatt en tatovering i fylla",
    "prøver seg på flest",
    "lager mest drama",
    "bor finest",
    "spiser mest drit",
    "ser best ut i undertøy",
    "er mest kresen",
    "er best i fotball",
    "har minst kontroll i fylla",
    "har mest kontroll i fylla",
    "har vært i flest land",
    "sitter mest på sofaen",
    "kjøpte en angrepille sist",
    "har finest legger",
    "ser best ut på håret",
    "har mest fylleangst",
    "sender oftest fyllameldinger",
    "er mest nikotinavhengig",
    "melder mye uten å faktisk gjøre det",
    "er mest soss",
    "har sendt flest nakenbilder",
    "er mest spontan",
    "debuterte først",
    "får mest likes på insta",
    "tåler mest alkohol",
    "har vært på flest tinderdates",
    "er mest villmann",
    "er størst stalker",
    "har finest dialekt",
    "kødder mest",
    "er snillest",
    "har vært mest på legevakten",
    "har best musikksmak",
    "har verst musikksmak",
    "hoster mest vorsj/fest"
]

function Questions(props){
    return questions.sort(() => Math.random() - 0.5);
}


export default Questions;