const questions = {
    Q1: 'har mest milf mor?',
    Q2: 'har den fineste søsteren?',
    Q3: 'skal chugge resten av glasset', 
    Q4: 'Hadde du donert en nyre til kompisen til høyre for deg?',
    Q5: 'hvem kommer til å dø av koffein overdose?',
    Q6: 'er mest biff?',
    Q7: 'er den mest skittne i senga?',
    Q8: 'hadde sett best ut som en jente?',
    Q9: 'er mest keeg? s/o @groggymenn2 ',
    Q10: 'hadde du ikke latt søsteren din ha med hjem?',
    Q11: 'drar ikke hjem med en dame idag?',
    Q12: 'drar til asia for å finne seg kone?',
    Q13: 'får klamydia først',
    Q14: 'tar med seg smårips hjem fra byen?',
    Q15: 'månetlig abonnement på tinder gold?',
    Q16: '',
    Q17: '',
    Q18: '',
    Q19: '',
    Q20: '',
    Q21: '',
    Q22: '',
    Q23: '',
    Q24: '',
    Q25: '',
    Q26: '',
    Q27: '',
    Q28: '',
    Q29: '',
    Q30: '',
};

export default questions;